### PR TITLE
News Week Demo using Bootstrap 4

### PR DESCRIPTION
**Pull request by Tahirbhalli**
This is a demo of a news website.
This page is created with html5 and bootstrap4

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Comment by Tahirbhalli** [comment]
> ## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

< Can you explain what I have to change to approve this project because you didn't mention any details

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Tahirbhalli        
#### Great Job so far, but there are a few more things required. 
### General
- [x] The Pull Request should have a meaningful  short description.
- [x] Note on your next project Commits should be descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] For the Comments in your code: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### Nav
##### Medium Screen
- [x] Those links  should disappear when viewed in medium screen, Lets fix the navbar
- [x] Please position well the newsweek, sign in and subscribe button and also add the hamburger menu.
#### Yours


#### Original 

##### Small Screen
- [x] Give space to the  sign in and subscribe button and also add the hamburger menu.
 
### Main content
##### Medium Screen
- [x]  For the Opinion, Latest news and More stories section the images are too big, it should look similar  to the original
### Opinion

### Latest News

### More Stories

- [x] The `In the magazine` section is fixed, remove that .in addition it should look more like the original

- [x] Give it space

##### Small Screen
###### Section Positioning
 - [x] Please follow the structure for the first 4 sections in this screen size:
TOP STORY
MORE STORIES
CULTURE & TRAVEL
FEATURED STORIES

- [x] Please work on this 
## Yours

## Original

- [x] In the  ***the magazine section*** the image is overlapping the text.

- [x] The texts are overlapping ,That should be fixed

- [x] The image needs space on the right 



## Footer
##### Medium Screen
- [x] The newsletter should come under subscribe,in addition work on the image in newsletter section
### Yours


### Original


##### Small Screen
- [x] Please fix the ovelapping error

### Implementation details
- [x] It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))

### Make changes and submit another code review request.
*Happy coding*

**Comment by Tahirbhalli** [comment]
> ## Hi @Tahirbhalli 
> #### Great Job so far, but there are a few more things required.
> ### General
> * [x]  The Pull Request should have a meaningful  short description.
> * [x]  Note on your next project Commits should be descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [x]  For the Comments in your code: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [x]  Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.
>   
> 
> ### Nav
> ##### Medium Screen
> * [x]  Those links  should disappear when viewed in medium screen, Lets fix the navbar
> * [x]  Please position well the newsweek, sign in and subscribe button and also add the hamburger menu.
> 
> #### Yours
> 
> 
> #### Original
> 
> 
> ##### Small Screen
> * [x]  Give space to the  sign in and subscribe button and also add the hamburger menu.
> 
> ### Main content
> ##### Medium Screen
> * [x]   For the Opinion, Latest news and More stories section the images are too big, it should look similar  to the original
> 
> ### Opinion
> 
> 
> ### Latest News
> 
> 
> ### More Stories
> 
> 
> * [x]  The `In the magazine` section is fixed, remove that .in addition it should look more like the original
>   
> * [x]  Give it space
>   
> 
> ##### Small Screen
> ###### Section Positioning
> * [x]  Please follow the structure for the first 4 sections in this screen size:
>   TOP STORY
>   MORE STORIES
>   CULTURE & TRAVEL
>   FEATURED STORIES
> * [x]  Please work on this
> 
> ## Yours
> 
> 
> ## Original
> 
> 
> * [x]  In the  _**the magazine section**_ the image is overlapping the text.
>   
> * [x]  The texts are overlapping ,That should be fixed
>   
> * [x]  The image needs space on the right
>   
> 
> ## Footer
> ##### Medium Screen
> * [x]  The newsletter should come under subscribe,in addition work on the image in newsletter section
> 
> ### Yours
> 
> 
> ### Original
> 
> 
> ##### Small Screen
> * [x]  Please fix the ovelapping error
>   
> 
> ### Implementation details
> * [x]  It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))
> 
> ### Make changes and submit another code review request.
> _Happy coding_

Done

**Review by MarioDena — CHANGES_REQUESTED** [review]
Code review by __Mario Enrique Delgado Naranjo__

Hello Tahirbhalli, great effort on your project! It's starting to look closer to the original and your code is cleaner. However some changes are still required, in order to approve the project.

## Changes required:heavy_exclamation_mark:

- [ ] Let's fix the page body, as you can see on the following screenshots the body needs to be inside a container to show a margin on bigger resolutions.
### Original
![Original1][Original1]
### Your project
![Project1][Project1]


- [x] The navbar needs to be adjusted, the "Newsweek" logo should be centered.
### Original
![Original2][Original2]
### Your project
![Project2][Project2]


- [x] The "Opinion" Images should not scale so much, on a small resolution they look tiny, and on a big one they look to big.
### Original
![Original3][Original3]
### Your project
![Project3][Project3]


- [x] "In the magazine's" images scale incorrectly on small and medium sizes
### Screenshot
![Original4][Original4]

- [x] The "subscribe" section's images need correction. the width is making it look distorted.
### Original
![Original5][Original5]
### Your project
![Project5][Project5]


- [x] On small sized there is overlapping with a button and the title text.
![Project7][Project7]
 

Please make the required changes and resubmit your project for review.

Keep up the good work, and Happy coding!

Code review by __Mario Enrique Delgado Naranjo__

[Original1]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview1.jpg
[Project1]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview1project.jpg
[Original2]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/navbaroriginal.jpg
[Project2]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/navbar.jpg
[Original3]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview2.jpg
[Project3]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview2project.jpg
[Original4]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview3original.jpg
[Project4]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview4project.jpg
[Original5]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview4.jpg
[Project5]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview4project.jpg
[Project7]: https://raw.githubusercontent.com/MarioDena/reviewImages/master/breview7.jpg

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Tahirbhalli 

### Good job so far :clap: However, you have a few changes to work on before your project could be approved
- Avoid squeezing your images, instead, you can define an image width 100% and control its height
squeezed image

### Make this change and resubmit for another review
- Happy coding!
- For assistance, contact me on @rOluochKe

**Comment by majovanilla** [comment]
Hi @Tahirbhalli 

## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- You didn't adjust the images as requested in the previous review. Check all the images you use, because you have more that don't behave like the original one. See screenshot. 👇 
Screenshot from 2020-02-19 17-14-01

Screenshot from 2020-02-19 17-13-41

- In a previous code review, you had an overlapping of the last section (subscribe) which hasn't been fixed. See screenshot:
Screenshot from 2020-02-19 17-19-31

- You didn't adjust the body of your page so that it behaves like the original page. It's always 100% width and it shouldn't


## Please, make all REQUIRED changes that my colleague Adama Chubiyojo Desmond sent you and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to introduce you and say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!

### Good job in making the required changes, however, you still need to make a few more changes
- Put more effort in making your project respond to different devices, images, text, spacing. See below some of the screenshots
center text
hidden content
image full width
image stretch
signup
small screen

- Make these changes and resubmit for another review. I wish all the best.
- For assistance, contact me on @rOluochKe 
- Happy coding!

**Comment by Tahirbhalli** [comment]
> Hello Team!
> 
> ### Good job in making the required changes, however, you still need to make a few more changes
> * Put more effort in making your project respond to different devices, images, text, spacing. See below some of the screenshots
>   center text
>   hidden content
>   image full width
>   image stretch
>   signup
>   small screen
> * Make these changes and resubmit for another review. I wish all the best.
> * For assistance, contact me on @rOluochKe
> * Happy coding!

done

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Tahirbhalli :handshake: 

### Thank you for doing most of the previous reviewers requested changes :medal_sports: your project is looking better and better with each submission :art: :eyes: and your use of bootstrap classes is remarkable :star: 

### I have noticed some important changes you have yet to accomplish from the previous reviews and also some changes I have marked as [OPTIONAL] because they weren't spotted in past reviews so please address at least all the ones without the [OPTIONAL] tag :point_down: 

## Small screens

**Section Positioning**

- [x] please follow the structure for the first 4 sections in this screen size (as it was requested in the first review), also the sections should be static in the page, yours are currently scrolling, so remove the scroll for this screen size:

1. TOP STORY
2. MORE STORIES
3. CULTURE & TRAVEL
4. FEATURED STORIES

- Yours

image

- Original

image

**MORE STORIES,  and the aside articles for the U.S, World, Business, Tech & Science, Culture and Sports**

- [ ] [OPTIONAL] The image for the articles of these sections should take 60% of the screen width and the content only 40% (I'm sorry this wasn't pointed out before)

- Yours

image

- Original

image

**CULTURE & TRAVEL**

- [x] as it was pointed out in the first review, the articles should take 100% of the screen width, you are also missing the heading **CULTURE & TRAVEL**  for this section. let's fix it!

- Yours

image

- Original

image

**IN THE MAGAZINE**

- [ ] [OPTIONAL] The IN THE MAGAZINE heading should come after the preview magazine and the preview magazine should be bigger in height (I'm sorry this wasn't pointed out before)

- Yours

image

- Original

image

**SUBSCRIBE and NEWSLETTER**

- [x] This wasn't pointed out before because you had an overlapping content and you fix this so as a follow-up review notice the images should come before the content and the content should be center in the page for both of this sections, and the **NEWSLETTER** image should take 100% of the screen width (let's make it look like the original)

- Yours

image

- Original

image

**Footer**

[OPTIONAL] The copyright and  social icons should come after the NEWSWEEK logo in separate rows, yours are overlapping (I'm sorry this wasn't pointed out before)

- Yours

image

- Original

image

## Small and Medium Screens

**Navbar**

- [x] The date should be hidden at this point and is still showing, and the NEWSWEEK logo should be at the leftmost part (follow-up of the first review)

- Yours

image

- Original

image

## Medium Screens

**FEATURED STORIES, TOP STORY, CULTURE & TRAVEL, OPINION and LATEST NEWS**

- [ ] [OPTIONAL] these sections should be static in the page but currently, they are scrolling so they seem hidden in the page, please remove the scroll

- Yours

image

- Original

image

**MORE STORIES**

- [x] As a follow up from the first review, your images should have less hight, try deleting some of the text content

- Yours

image

- Original

image

**LATEST NEWS**

- [x] The images should take 10% of the page and the heading 90% (follow up from the first review)

- Yours

image

- Original

image

**U.S, World, Business, Tech & Science, Culture and Sports**

- [x] [OPTIONAL] The image for the aside articles of these sections should take 30% of the article width and the content 70% in other words, make the images smaller only for the aside articles (I'm sorry this wasn't pointed out before)

- Yours

image

- Original

image

**SUBSCRIBE and NEWSLETTER**

- [x] the NEWSLETTER section has to come after the SUBSCRIBE section like the original (follow-up from the first review)

- Yours

image

- Original

image

## Big Screens

**Navbar**

- [x] Follow up: the NEWSWEEK logo should be more centered in the page and the navigation links  should be better distributed in the navbar, make the search space smaller

- Yours

image

- Original

image

**FEATURED STORIES, TOP STORY, OPINION, CULTURE & TRAVEL, MORE STORIES and LATEST NEWS**

- [ ] [OPTIONAL] remove the scroll from these sections as they should be static in the page like the original

- Yours

image

- Original

image

## General

**Navbar

* [ ] [OPTIONAL] Sign In and Subscribe should be in all caps like the original

**FEATURED STORIES, TOP STORY, OPINION, CULTURE & TRAVEL, MORE STORIES and LATEST NEWS**

* [ ] [OPTIONAL]the titles should be capitalized and color light gray

**NEWSLETTER**

* [ ] [OPTIONAL] replace the header "NEWS CASTLER" with "NEWSLETTER"

### That's it! :raised_hands: 

### Please :pray: do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @Tahirbhalli, well done, but there are some requested changes that you haven't effected.**

1. The order of sections in the first four sections on small screens as pointed out in previous reviews is still not fixed.

2. The scrollbars in those sections pointed out in the previous review hasn't been removed.

3. In the previous review, it was pointed out that the date should be hidden from the header for small and medium screen sizes. You have only taken care of the small screen size yet.

4. On medium screen size, the subscribe and newsletter section which you brought side by side based on the previous review are to be of equal heights.

image

These changes have been pointed out as mandatory for your project to be approved.

**_Kindly make them and submit another code review request_**

**Good luck.**

**Comment by majovanilla** [comment]
Hey @Tahirbhalli , 👋

## Good job on implementing the requested changes on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍
These changes were requested by the previous reviewers but are still pending.

### Required Changes: ✍️

- You are still missing the heading CULTURE & TRAVEL for this section.

 - As stated in the second review, your Newsletter and Subscribe sections were overlapping, making it difficult to see the details. You fixed the first part, but now the image is overlapping on the footer in small screen size. See screenshot below:

Screenshot from 2020-02-20 23-38-39

- You are almost done with those sections!! Check the medium screen size (pointed out in the previous review) so that you can see what you are missing. Screenshot:

Screenshot from 2020-02-20 23-44-59

### Optional Changes:

If you want to make your project even better 🔥💥, I strongly suggest you to complete the OPTIONAL changes that my colleagues pointed out in the previous reviews. This will make your work look more professional.  

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @Tahirbhalli you have done a great job implementing some of the changes requested by the previous reviewers: 👍  However, for the project to be approved, we need to fix the comments highlighted. 🎖  Check comments below:
- We have linter errors, kindly fix them
mn
- Kindly fix the ```Culture and Travel``` section. It is missing. Check original for reference
mn1
```In Small Screen``` culture and travel looks like this
mn3
- In the previous review, the reviewer made mention of the order in which the following are arranged. Kindly follow them.
``` 
   TOP STORY 
   MORE STORIES
   CULTURE AND TRAVEL
   FEATURED STORIES
``` 
in that order. Kindly fix them.

Kindly make these changes and submit another code review 😄 
Happy coding 💻 
Daniel Larbi Addo

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Tahirbhalli 

### Good job :clap: in implementing the changes, you still have a few left to solve before your project can be approved.
- Fix the image at the right side of your footer, it is squeezed 
fix the image
- On medium screen, these images are still not looking good them by making them responsive 
media screen devices
- On mobile devices, there are content on top of each other example
res overlapping
- Also, fix this button and text on small devices
small devices
- On your sidebar on the latest news section, you have so many content there making it crowded, reduce the number of list items you are displaying
too crowded

### Make these changes and resubmit for another code review. Good luck!
- For assistance, contact me on @rOluochKe 
- Happy coding!

**Comment by SofiBretz** [comment]
### Well done Team 👏

This page works smoothly ✨.

Project Approved! 
**You can merge 👍**

SofiBretz.

**Pull request merged**
